DotOp merge optimization.
alibaba/BladeDISC pull request #203
Opened 2022-03-29 09:03 UTC by wangdalin

Merge Several DotGeneralOp with same one-side operand together.

2022-03-29 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/BladeDISC?pullRequest=203) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/BladeDISC?pullRequest=203) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/BladeDISC?pullRequest=203) it.</sub>

2022-03-29 09:46 UTC, JamesTheZ requested changes

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +std::pair<int64_t,int64_t> getMNDim(mhlo::DotGeneralOp op) {
This function is only used by `DotShareOperandMergeConverter`. Better to make it private.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +    ShareType share_type;
This member is not used. Please remove it.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +    int64_t rhs_contracting_dim;
It is not enough to log only contracting dims. It requires all dims the same layout. Please use the overall dim-numbers and add UT to test different layouts.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +    assert("share_type error");
We do not need this branch as the calling of this function is under control.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +    // printf("is_dynamic_shape = %d\n", is_dynamic_shape);
Please remove all unused comments.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +                                        lhs_batch_dims.end());
Miss alignment. Format with `pre-commit run` or `git-clang-format`.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +  if (!is_dynamic_shape) {
`is_dynamic_shape` only check whether `k` dim is dynamic or not. We do not whether other dims are dynamic or not.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +      if (concat_dim_size == -1) {
Use `ShapedType::kDynamicSize` instead of `-1`.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +          rhs_shapes[i] = -1;
Do not need to update as the value is already `ShapedType::kDynamicSize` when building the vector.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +  if(share_type == LEFT){
Merge the two large branches to reduce redundant code.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +  // Build slice  for each of the original dot op, and replace the dot.
Nit: 1) an extra space in the comment; 2) add line between function blocks and remove line between the comment and its corresponding function block.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +      SmallVector<int64_t> strides(result_rank, 1);
What if the original stride is not 1? We may filter out dots whose stride is not one when clustering dots.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +          start[j] = 0;
Better the specify the init value of `start` as `0` when creating this vector. And only initialize `start[concat_dim]` outside the loop.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
>    ShapeAnalysis analysis(func_);
Why change this function.

2022-03-29 09:46 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +    signalPassFailure();
We may signal pass failure only if all the two phases are failed.

2022-03-30 12:33 UTC, linearhit reviewed
Shall we add some FILECHECK UTs?

2022-03-31 03:11 UTC, JamesTheZ requested changes
Most functions look good now, except you need to get the concat-dim-in-result as in detailed comments. Some code can be more neat. Please refer to https://github.com/JamesTheZ/BladeDISC/commit/73442372b5204f318787917371d2d0c0ebd45a8a for some refactor.

2022-03-31 03:11 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +  // Build relust DotGeneralOp
Typo.

2022-03-31 03:11 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +        if (j == concat_dim) {
You need a `concat-dim-in-result`.

2022-03-31 03:11 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +          start[j] = concat_dim_start;
No need to put in the loop.

2022-03-31 03:11 UTC, JamesTheZ commented on tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
> +      SmallVector<int64_t> start(result_rank, 0);
No necessary to update this function?

2022-03-31 08:48 UTC, JamesTheZ approved these changes
LGTM

2022-03-31 08:49 UTC, merged