[disc-cpu] Add a TensorFlow cpu inference demo on X86 platform
alibaba/BladeDISC pull request #73
Opened 2022-01-21 07:47 UTC by wyzero

2022-01-22 01:04 UTC, linearhit requested changes

2022-01-25 02:08 UTC, wyzero commented on docs/tutorials/tensorflow_inference_and_training.md
> +### All You Need Are the Two Lines With CPU Specific Setting!
It's just comment！？

2022-01-25 02:27 UTC, wyzero commented on README.md
> +|  X86       |    Yes        |    Yes                 |    Yes               |
done, Thanks!

2022-01-25 02:28 UTC, wyzero commented on docs/tutorials/tensorflow_inference_and_training.md
> +### All You Need Are the Two Lines With CPU Specific Setting!
done!

2022-01-25 02:29 UTC, linearhit approved these changes
LGTM

2022-01-25 03:15 UTC, merged